language: c
dist: trusty
sudo: true
compiler:
- clang
- gcc

before_install:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl2-image-dev
    - libsdl2-dev
    - gcc-4.9

script: make SDL2_CFLAGS="`sdl2-config --cflags`" SDL2_LDLIBS="`sdl2-config --libs` -lSDL2_image"