language: c
dist: trusty
sudo: true
compiler:
- clang
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl2-dev

before_script:
  - mkdir bin
  - cd bin
  - cmake ..

script: make